site_name: tanzu-developer-portal
site_description: Tanzu Developer Portal
site_author: user:ben.wilcock
nav:
  - "Welcome To Tanzu Developer Portal": index.md
  - "Getting Started With Tanzu Developer Portal": get-started.md
  - "Why Choose Tanzu Developer Portal?": why-choose-tdp.md
  - "Feature Highlights Of Tanzu Developer Portal": features.md
  - "What's Included With Tanzu Developer Portal": whats-in-the-box.md
  - "Getting Help With Tanzu Developer Portal": help.md
  - "FAQs": faqs.md
  # - 'Tanzu Labs - Modernization Recipes':
  #   - 'REST API Design': recipes/rest-api-design.md
  #   - 'REST API Versioning' : recipes/rest-api-versioning.md
  #   - 'Get Started With Git': recipes/get-started-with-git.md

plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system